name: Deploy to Server

on:
  push:
    branches:
      - main   # change to your deploy branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo 'testing workflow! Running `ls -al'
            ls -al
            echo 'about to `cd ~/Ren-chan`!'
            cd ~/Ren-chan
            echo 'Running `ls -al` again!'
            ls -al
            echo 'Running `./deploy.sh`'
            ./deploy.sh
