name: Deploy to Server

on:
  push:
    branches:
      - main   # change to your deploy branch if needed
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # note that I can't run `./deploy.sh` as is, because it needs
          # pipenv in the PATH. It won't be unless it's a login shell,
          # so I need to force it to run in a login shell with `bash -l`
          script: |
            cd ~/Ren-chan
            bash -l deploy/deploy.sh
